### ISSUE TITLE
Getting a 404 Error on any Model

### ISSUE THREAD

**Issue by cybereality** [Cadiducho/flarum-sketchfab#1]
Trying to use this extension with the latest version of Flarum and I get a Sketchfab window, but it says 404 error.

**Comment by cybereality** [comment]
Actually, it looks like the plugin is just not compatible with Flarum 1.7.2. It was corrupted before but I removed it and now it won't let me reinstall cause it says it conflicts with my requirements.

**Comment by Cadiducho** [comment]
> Trying to use this extension with the latest version of Flarum and I get a Sketchfab window, but it says 404 error.

Hi, what link are you using? I'm triying with a model and it seems to work for me

In sketchfab website, you have to click in "embed" (between to "Add To" and "Share"), click the checkbox that says "Use BBCode" and copy that BBCode, which is a [sketchfab] tag with the ID of the model
![image](https://user-images.githubusercontent.com/3594924/232025127-fa6ed493-6cb2-4768-b0a4-8fa9372f9d8a.png)

**Comment by cybereality** [comment]
I did try that and it didn't work. Either way, I cannot use the plugin anymore since I uninstalled it and now it won't let me reinstall because it says it doesn't work with my requirements or minimum stability. I tried beta and it still didn't work. Not sure what the problem is.

**Comment by Cadiducho** [comment]
I recreated the version in packagist. Now you should be able to install it with the following command:
composer require cadiducho/flarum-sketchfab

**Comment by cybereality** [comment]
I works now!!! Thank you so much.
